{% set version = '1.0-6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vgam
  version: {{ version|replace("-", "_") }}

source:
  fn: VGAM_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/VGAM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/VGAM/VGAM_{{ version }}.tar.gz
  sha256: 121820a167411e847b41bdcb0028b55842d0ccc0c3471755c67449837e0fe3b9

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('VGAM')"           # [not win]
    - "\"%R%\" -e \"library('VGAM')\""  # [win]

about:
  home: https://www.stat.auckland.ac.nz/~yee/VGAM
  license: GPL-3
  summary: 'An implementation of about 6 major classes of statistical regression models. The
    central algorithm is Fisher scoring and iterative reweighted least squares. At the
    heart of this package are the vector generalized linear and additive model (VGLM/VGAM)
    classes. VGLMs can be loosely thought of as multivariate GLMs. VGAMs are data-driven
    VGLMs that use smoothing. The book "Vector Generalized Linear and Additive Models:
    With an Implementation in R" (Yee, 2015) <DOI:10.1007/978-1-4939-2818-7> gives details
    of the statistical framework and the package. Currently only fixed-effects models
    are implemented. Many (150+) models and distributions are estimated by maximum likelihood
    estimation (MLE) or penalized MLE. The other classes are RR-VGLMs (reduced-rank
    VGLMs), quadratic RR-VGLMs, reduced-rank VGAMs, RCIMs (row-column interaction models)---these
    classes perform constrained and unconstrained quadratic ordination (CQO/UQO) models
    in ecology, as well as constrained additive ordination (CAO). Note that these functions
    are subject to change; see the NEWS and ChangeLog files for latest changes.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - croth1
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
