# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortrantarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_forttarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KW7nOpm3GJVkwsNzKc3VqrPDh/riVGWcF/ZwsbNnJBtxDkxPPVcTtl2G0uDN7xw79klZJvLnQBBugxR4R48iZe6TkmRaV4pJTnI8O+/2EkPsktTCLtimYJbABGM2mBOVAKQ4FQrFvozdBXocBr2lE2ySji79d3QayJmtQX0lX8YnseHkjWlF8nJtc1ywLaPhsXfdjloyyxpByk8uiY4MZ71Bs1ZD+W3LVP59xOR2tREfkvZ27/VXAKY5MZsFZHbjruQFxYevRP1CPIpDLVThB86E3gMoy4LTuhr9EWo5P46SxL7qpNIVRPAz3lOst/J0whYFB8O0L1Q5pBGxF5/HIDKoUAyrY1uMJy5G4KTmaz6qombdX4OqJNRjsbqJb6qWCyBw2kL0dRDoxUBjSNusrHr4rF70nHWrNMN1soW5ypvtB6HW0znxqiegOB5L4TwDIPUOp1JqpBGVDbHbi8wBAg/NlW0OLjOFSn3mh9noNc9fVrigDJiucTWd/JakZuK6LPiD7XvL4M0fp4FrlmlskR3YTYs4v+fiFzOatbGS8gV5GpU6Rri/BKMEfIZ8Vpg7CrUkyYkGiO2tM5M43tfddSugcHW6tcsr1QQpKunvd+dsis7GSEfpQRYHzrzBpm6nq6cR1MCwdzsbGMHwcGmFE3zUWafxvpnnh1PsSNbxGag="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
