appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: KW7nOpm3GJVkwsNzKc3VqrPDh/riVGWcF/ZwsbNnJBtxDkxPPVcTtl2G0uDN7xw79klZJvLnQBBugxR4R48iZe6TkmRaV4pJTnI8O+/2EkPsktTCLtimYJbABGM2mBOVAKQ4FQrFvozdBXocBr2lE2ySji79d3QayJmtQX0lX8YnseHkjWlF8nJtc1ywLaPhsXfdjloyyxpByk8uiY4MZ71Bs1ZD+W3LVP59xOR2tREfkvZ27/VXAKY5MZsFZHbjruQFxYevRP1CPIpDLVThB86E3gMoy4LTuhr9EWo5P46SxL7qpNIVRPAz3lOst/J0whYFB8O0L1Q5pBGxF5/HIDKoUAyrY1uMJy5G4KTmaz6qombdX4OqJNRjsbqJb6qWCyBw2kL0dRDoxUBjSNusrHr4rF70nHWrNMN1soW5ypvtB6HW0znxqiegOB5L4TwDIPUOp1JqpBGVDbHbi8wBAg/NlW0OLjOFSn3mh9noNc9fVrigDJiucTWd/JakZuK6LPiD7XvL4M0fp4FrlmlskR3YTYs4v+fiFzOatbGS8gV5GpU6Rri/BKMEfIZ8Vpg7CrUkyYkGiO2tM5M43tfddSugcHW6tcsr1QQpKunvd+dsis7GSEfpQRYHzrzBpm6nq6cR1MCwdzsbGMHwcGmFE3zUWafxvpnnh1PsSNbxGag=
conda_forge_output_validation: true
